CREATE TABLE IF NOT EXISTS CONFIG(
        ID                   INT PRIMARY KEY NOT NULL,
        ELECTION_START_EPOCH INT             NOT NULL,
        ELECTION_END_EPOCH   INT             NOT NULL,
        ELECTIONS_SERIALIZED TEXT            NOT NULL
);

CREATE TABLE IF NOT EXISTS VOTER_DEVICES(
        ID         INT PRIMARY KEY NOT NULL,
        PUBLIC_KEY TEXT            NOT NULL
);

CREATE TABLE IF NOT EXISTS RECORDED_BALLOTS(
        VOTER_DEVICE_ID              INT PRIMARY KEY NOT NULL,
        CAST_AT_EPOCH                INT             NOT NULL,
        RECORDED_AT_EPOCH            INT             NOT NULL,
        CANDIDATE_CHOICES_SERIALIZED TEXT            NOT NULL,
        VOTER_DEVICE_SIGNATURE       TEXT            NOT NULL,
        VOTE_SERVER_SIGNATURE        TEXT            NOT NULL,

        FOREIGN KEY(VOTER_DEVICE_ID) REFERENCES VOTER_DEVICES(ID)
);
